-- Seed: tasks from tracker.csv
-- Generated 2026-08-03T16:45:17.318Z

insert into tasks (title, subteam_tags, status, month_bucket) values
  ('Host new board social!', ARRAY['Co-Chairs'::subteam_enum], 'done'::task_status_enum, '2026-04'),
  ('Visitas Fair', ARRAY['Co-Chairs'::subteam_enum], 'done'::task_status_enum, '2026-04'),
  ('Update WECode Guidebook', ARRAY['Co-Chairs'::subteam_enum], 'done'::task_status_enum, '2026-04'),
  ('Invite WECode 2026 co-chairs (Kitty, Hannah) + graduating directors to join Alumni Board of Advisors', ARRAY['Co-Chairs'::subteam_enum], 'in progress'::task_status_enum, '2026-04'),
  ('Onboard Google Drive, Ramp, Slack', ARRAY['All-Board'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Begin draft of All-Team Constitution (role definitions, decision rights, deadlines)', ARRAY['All-Board'::subteam_enum], 'in progress'::task_status_enum, '2026-05'),
  ('Set up regular summer meeting cadence with directors', ARRAY['Co-Chairs'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Formalize Alumni Board of Advisors: advisor agreement (1 page, expectations + time commitment), monthly check-in cadence (first Saturday of month, 30 min)', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-05'),
  ('Finalize All-Team Constitution — share with all directors for review', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-05'),
  ('Decide on event venue & date', ARRAY['Logistics'::subteam_enum], 'in progress'::task_status_enum, '2026-05'),
  ('Logistics handoff meeting', ARRAY['Co-Chairs'::subteam_enum,'Logistics'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Sponsor outreach', ARRAY['Finance'::subteam_enum], 'in progress'::task_status_enum, '2026-05'),
  ('Pull 2026 outreach spreadsheet: identify companies that said ''follow up for 2027'' and begin warm outreach BEFORE April ends', ARRAY['Finance'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Begin warm outreach to past mentors/speakers — ask if their companies want to sponsor', ARRAY['Finance'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Survey 2026 master outreach spreadsheet: categorize ghosted vs. interested vs. declined vs. to-revisit', ARRAY['Finance'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Onboard GMass or Apollo.io for mass outreach at scale', ARRAY['Finance'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Draft 2027 sponsorship prospectus', ARRAY['Marketing & Strategy'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Organize all 2026 brand assets with organized tagging (color codes, logo files, media pack)', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-05'),
  ('Create 1-page brand guide PDF: hex codes, fonts, logo usage, Lottie usage, color palette enforcement rules — share in #pub-requests Slack', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-05'),
  ('Theme for 2027', ARRAY['Programming'::subteam_enum], 'done'::task_status_enum, '2026-05'),
  ('Transfer GitHub and Supabase credentials/ownership away from single person — document new owners', ARRAY['Engineering'::subteam_enum], 'not started'::task_status_enum, '2026-05'),
  ('Write infrastructure doc: architecture diagram, known bugs, feature roadmap, deployment process.', ARRAY['Engineering'::subteam_enum], 'not started'::task_status_enum, '2026-05'),
  ('Decide on 2027 theme', ARRAY['All-Board'::subteam_enum], 'done'::task_status_enum, '2026-06'),
  ('Continue cold + warm sponsor outreach — target 3–4 commitments before board retreat', ARRAY['Finance'::subteam_enum], 'done'::task_status_enum, '2026-06'),
  ('Speaker outreach', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Begin keynote outreach', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Re-engage Tracy Chou (BlockParty) — said she''d be open after 2026 couldn''t make it', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Re-engage Melanie Perkins (Canva) — couldn''t make 2026 due to dates', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Contact Navrina Singh (navrina@credo.ai) — explicitly said open to 2027', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Attempt Fei-Fei Li via the Google Form + direct email', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Design 2027 logo', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Begin website refresh with new theme branding once theme is confirmed with Programming', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Design 2027 logo / visual identity', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Plan feature roadmap: multiple profile links, remove events from schedule page, fix group tickets, consider portal-native ticketing to remove Eventbrite dependency', ARRAY['Engineering'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Plan Eventbrite ↔ portal sync / Gather registration validation system', ARRAY['Logistics'::subteam_enum,'Engineering'::subteam_enum], 'not started'::task_status_enum, '2026-06'),
  ('Plan board retreat (target first weekend of October, same as 2026)', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Plan regular application promotion', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Alumni Board of Advisors Check in #1', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Design merch, ID cards, certificates', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Design physical merch (attendee t-shirts, board quarter-zips, hats, lanyards, sticker packs, speaker gift notebooks)', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Venue decision finalized and contract signed', ARRAY['Logistics'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Begin catering research — partnerships, identify vendors, get quotes, decide on menu', ARRAY['Logistics'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Continue sponsor outreach — follow up on all May/June contacts', ARRAY['Finance'::subteam_enum], 'in progress'::task_status_enum, '2026-07'),
  ('Continue keynote and solo speaker outreach', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Build list of past WiCS + WECode board members for mentor sourcing pipeline', ARRAY['Engagement'::subteam_enum], 'not started'::task_status_enum, '2026-07'),
  ('Freshman Extracurricular Fair', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('Second Alumni Board of Advisors check-in — specific ask: keynote speaker intros', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('Finalize board retreat logistics: location, schedule, transportation, housing', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('AD recruiting cycle: post and pub applications', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('Apply for SEAS and HUA grants', ARRAY['Finance'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('Judge/mentor outreach', ARRAY['Engagement'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('Decide on event catering options', ARRAY['Logistics'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('Plan early application/ticketing promotion strategy with pub tracker setup', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-08'),
  ('Back-to-school social!', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('Establish weekly team meeting cadence + all-board schedule', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('Set up sibling/meal pairing program structure for the year — assign pairs before retreat', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('Goal: 3–4 sponsor commitments secured before board retreat', ARRAY['Finance'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('Portal MVP complete — all core features functional before retreat', ARRAY['Engineering'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('Tech Fellow application opens in September — same cadence as 2026', ARRAY['Engagement'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('Begin mentor outreach via Harvard alumni directory (higher response rates than LinkedIn)', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('Reach out to HGWISE (Harvard Graduate Women in Science and Engineering) & Global Women Empowerment for mentors', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-09'),
  ('RETREAT', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('All-board photos (Widener Steps)', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('First sibling/meal pairing round assigned — pairs meet this month', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Place food orders', ARRAY['Logistics'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Scholarship application opens; begin outreach', ARRAY['Finance'::subteam_enum,'All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Full speaker outreach in swing', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Third Alumni Board of Advisors check-in — specific ask: sponsor intros', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Ticketing: set early bird + general admission pricing; open early bird sales', ARRAY['Co-Chairs'::subteam_enum,'All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Tech Fellow selection completed', ARRAY['Engagement'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Begin planning pre-conference events — marketing must start December 1 at the latest', ARRAY['Engagement'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('Innovation Challenge Judge sourcing', ARRAY['Engagement'::subteam_enum], 'not started'::task_status_enum, '2026-10'),
  ('All Board Social', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-11'),
  ('Volunteer recruitment active', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2026-11'),
  ('Reaching out judges and mentors', ARRAY['Engagement'::subteam_enum], 'not started'::task_status_enum, '2026-11'),
  ('Begin housing host recruitment for conference weekend', ARRAY['Logistics'::subteam_enum], 'not started'::task_status_enum, '2026-11'),
  ('Portal demo for all-board', ARRAY['Engineering'::subteam_enum], 'not started'::task_status_enum, '2026-11'),
  ('Begin writing event outlines (fireside chat, keynote, panel, solo talk, workshop templates from 2026 exist)', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-11'),
  ('Scholarship selections finalized', ARRAY['Finance'::subteam_enum], 'not started'::task_status_enum, '2026-11'),
  ('Fourth Alumni Board of Advisors check-in — specific ask: last-minute speaker/mentor referrals if needed', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2026-12'),
  ('Design ID cards/lanyards, certificates', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-12'),
  ('Begin planning speaker reception venue (Winthrop JCR or equivalent — book early)', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2026-12'),
  ('Merch orders placed', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2026-12'),
  ('Full-board portal bug bash (with TF testers) — same as 2026, effective format', ARRAY['Engineering'::subteam_enum], 'not started'::task_status_enum, '2026-12'),
  ('Internal Run of Show master sheet finalized and shared with all-board', ARRAY['Co-Chairs'::subteam_enum], 'not started'::task_status_enum, '2027-01'),
  ('January social: ice skating at Frog Pond', ARRAY['All-Board'::subteam_enum], 'not started'::task_status_enum, '2027-01'),
  ('Set up Squareup for In-person merch store', ARRAY['Finance'::subteam_enum], 'not started'::task_status_enum, '2027-01'),
  ('All catering orders placed and confirmed by January 15', ARRAY['Logistics'::subteam_enum], 'not started'::task_status_enum, '2027-01'),
  ('Physical layout planned: tables, chairs, signage inventory — separate table for Project Exhibition vs. food', ARRAY['Logistics'::subteam_enum,'Programming'::subteam_enum], 'not started'::task_status_enum, '2027-01'),
  ('Pre-conference event marketing in full swing; all events listed on website with registration links', ARRAY['Engagement'::subteam_enum,'Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2027-01'),
  ('Moderator and A/V role sign-up spreadsheet shared; all board members sign up for at least 3 slots across Sat + Sun', ARRAY['Programming'::subteam_enum], 'not started'::task_status_enum, '2027-01'),
  ('Conference website: full in-person schedule, separate virtual schedule, speaker bios, engagement event descriptions all live', ARRAY['Marketing & Strategy'::subteam_enum], 'not started'::task_status_enum, '2027-01');

-- TASKS NEEDING TEAM ASSIGNMENT (3 rows)
-- Please assign a subteam_tags value to each before running:
-- Month: 2027-01 | "All virtual participants onboarded to Gather by January 15"
-- Month: 2027-03 | "Run Co-Chair 2028 Elections"
-- Month: 2027-03 | "Reimbursements"

-- Milestones from guidebook lifecycle table
insert into milestones (month, general_label, team_label, team) values
  ('Feb.', 'Pre-Conference Events / Conference', null, null),
  ('March', 'Post-Conference Processing / Co-Chair Elections / Co-Chair Onboarding', 'WECode Report', 'Engineering'::subteam_enum),
  ('April', 'Director Recruiting / Onboarding', null, null),
  ('September', 'AD Recruitment + Onboarding / Board Retreat', 'Theme/Branding Reveal', 'Programming'::subteam_enum),
  ('September', 'AD Recruitment + Onboarding / Board Retreat', 'Theme/Branding Reveal', 'Marketing & Strategy'::subteam_enum),
  ('October', 'Conference Planning / Winter Break', 'Venue Reveal', 'Logistics'::subteam_enum),
  ('November', null, 'Sponsor Reveal', 'Finance'::subteam_enum),
  ('November', null, 'Keynote Speaker Reveal', 'Programming'::subteam_enum),
  ('December', null, 'Tech Fellow Reveal', 'Engagement'::subteam_enum),
  ('January', null, 'Merch Drop', 'Marketing & Strategy'::subteam_enum);
